name: Feature Request
description: File a feature request
title: "[Feature]: "
labels: [feature]
body:
  - type: textarea
    id: describe
    attributes:
      label: Describe the feature you are requesting.
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why is this a good feature to have?
    validations:
      required: true
  - type: checkboxes
    id: pull-request
    attributes:
      label: Pull Request
      options:
        - label: If the feature was approved, would you be willing to submit a pull request and do it yourself?
